
x-common-variables: &common-variables
      POSTGRES_USER: nyc
      POSTGRES_PASSWORD: gis #${POSTGRES_PASSWORD}
      POSTGRES_DB: nyc
      POSTGRES_HOST: db
      POSTGRES_DRIVERNAME: postgresql
      PORT: 5432


services:
  db:
    container_name: db
    image: postgis/postgis:14-3.4
    restart: always
    environment: *common-variables
    ports:
      - "5432:5432"

  db-setup: # create extensions & schemas
    container_name: db-setup
    environment: *common-variables
    build:
      context: ..
      dockerfile: docker/Dockerfile

  alembic:
    container_name: alembic-setup
    image: python:3.11-slim-bullseye
    environment: *common-variables
    depends_on:
      - db
    command: >
      /bin/sh -c "
      alembic init alembic &&
      alembic revision --autogenerate -m 'Initial migration' &&
      alembic upgrade head"
