
x-common-variables: &common-variables
      POSTGRES_USER: nyc
      POSTGRES_PASSWORD: gis #${POSTGRES_PASSWORD}
      POSTGRES_DB: nyc
      POSTGRES_HOST: db
      POSTGRES_DRIVERNAME: postgresql
      PORT: 5432


services:
  db:
    container_name: db
    image: postgis/postgis:14-3.4
    restart: always
    environment: *common-variables
    ports:
      - "5432:5432"

  db-setup: # create extensions & schemas
    container_name: db-setup
    environment: *common-variables
    depends_on:
      db:
        condition: service_started
        restart: true
    build:
      context: ..
      dockerfile: docker/db_setup.Dockerfile

  # alembic:
  #   container_name: alembic-setup
  #   image: python:3.11-slim-bullseye
  #   environment: *common-variables
  #   depends_on:
  #     db-setup:
  #       condition: service_completed_successfully
  #       restart: true
  #   build:
  #     context: ..
  #     dockerfile: docker/alembic.Dockerfile
  #   command: >
  #     /bin/sh -c "
  #     alembic revision --autogenerate -m 'Initial migration' &&
  #     alembic upgrade head"
