"""test_002

Revision ID: a2fa8615269b
Revises: fbf2dd38133d
Create Date: 2024-09-06 18:45:45.549338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'a2fa8615269b'
down_revision: Union[str, None] = 'fbf2dd38133d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trajectory', sa.Column('some_new_field_ERRRRR', sa.String(), nullable=True), schema='gps')
    op.drop_column('trajectory', 'some_new_field', schema='gps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trajectory', sa.Column('some_new_field', sa.VARCHAR(), autoincrement=False, nullable=True), schema='gps')
    op.drop_column('trajectory', 'some_new_field_ERRRRR', schema='gps')
    # ### end Alembic commands ###
