"""test_02

Revision ID: b011fca27a94
Revises: fbf2dd38133d
Create Date: 2024-09-06 12:10:34.691538

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "b011fca27a94"
down_revision: Union[str, None] = "fbf2dd38133d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trajectory", "some_new_field", schema="gps")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trajectory",
        sa.Column("some_new_field", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="gps",
    )
    # ### end Alembic commands ###
