"""test_001

Revision ID: fbf2dd38133d
Revises:
Create Date: 2024-09-06 12:10:24.549138

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "fbf2dd38133d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feed_item",
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("create_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_time", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="gps",
    )
    op.create_index(
        op.f("ix_gps_feed_item_id"), "feed_item", ["id"], unique=False, schema="gps"
    )
    op.create_table(
        "trajectory",
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="GEOMETRYZM",
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("feed_item_id", sa.UUID(), nullable=True),
        sa.Column("some_new_field", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("create_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_time", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["feed_item_id"],
            ["gps.feed_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="gps",
    )
    op.create_index(
        op.f("ix_gps_trajectory_id"), "trajectory", ["id"], unique=False, schema="gps"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gps_trajectory_id"), table_name="trajectory", schema="gps")
    op.drop_table("trajectory", schema="gps")
    op.drop_index(op.f("ix_gps_feed_item_id"), table_name="feed_item", schema="gps")
    op.drop_table("feed_item", schema="gps")
    # ### end Alembic commands ###
