name: DB Change Checks

on:
  push

jobs:
  check-sql-schema-changes:
    runs-on: github-dev-runner
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v44
        id: changed-db-files
        with:
          files: |
            - "/app"
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        if: steps.check-sql-schema-changes.outputs.any_changed == 'true'
        with:
          python-version: '3.11'

      - name: Create new branch
        id: create-new-branch
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          title: "Create a new branch"
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
        run: |
          # Create a timestamp
          TIMESTAMP=$(date +'%Y%m%d%H%M')
          BRANCH_NAME="my-branch-$TIMESTAMP"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
          echo "Branch $BRANCH_NAME created and pushed."

  # run-alembic-script-gen:

  # open-pr:

  # tag-someone:

